Repository honeycombio/dynsampler-go, pull requests merged in 2022-11, with the labels that each got.

#36 ci: validate PR title
  .github/workflows/validate-pr-title.yml
Labels: type: maintenance, no-changelog, version: no-bump

#35 maint: update buildevents orb and move datasets
  .circleci/config.yml
Labels: version: no bump, type: maintenance, no-changelog

#39 maint: drop versions of go below 1.16
  .circleci/config.yml
Labels: version: bump minor, type: maintenance, breaking-change

#38 maint: add dependabot
  .github/dependabot.yml
Labels: version: no bump, no-changelog

#37 ci: update validate PR title workflow
  .github/workflows/validate-pr-title.yml
Labels: type: enhancement, no-changelog

#41 ci: add usual release procedures to this project
  .circleci/config.yml
  Makefile
  RELEASING.md
Labels: version: no bump, type: maintenance, no-changelog
