Repository honeycombio/dynsampler-go, pull requests merged in 2023-03, with the labels that each got.

#45 feat: Windowed Throughput Sampling
  blocklist.go
  blocklist_test.go
  windowedthroughput.go
  windowedthroughput_test.go
Labels: type: enhancement, version: bump minor

#55 maint: bump the go versions we support
  .circleci/config.yml
  go.mod
Labels: version: bump minor, type: maintenance

#53 feat: add GetSampleRateMulti
  avgsamplerate.go
  avgsamplerate_test.go
  avgsamplewithmin.go
  blocklist.go
  blocklist_test.go
  dynsampler.go
  emasamplerate.go
  emasamplerate_test.go
  genericsampler_test.go
  onlyonce.go
  perkeythroughput.go
  static.go
  totalthroughput.go
  windowedthroughput.go
Labels: type: enhancement, status: review needed, version: bump minor

#58 feat: EMAThroughput sampler
  emathroughput.go
  emathroughput_test.go
  genericsampler_test.go
Labels: type: enhancement, version: bump minor

#60 rel: Prep for v0.4.0 release
  CHANGELOG.md
  README.md
Labels: status: review needed
